---

# With the collection name, version, and source options

- src: https://github.com/paoven/ansible-docker/
  version: v1.10.4
  name: docker-daemon

- src: https://github.com/paoven/role-secure-docker-daemon
  version: v0.5
  name: secure-docker-daemon
