---


- hosts: "docker_nodes"
  roles:
    - role: "secure-docker-daemon"
      vars:
        dds_fetch_client_certs: yes

- hosts: "docker_nodes"
  roles:
    - role: "docker-daemon"
    - role: "enable-docker-daemon"

- hosts: "swarm_managers"
  roles:
    - role: "swarm-manager"

- hosts: "swarm_workers"
  roles:
    - role: "swarm-worker"
